// Type: WindowsInput.Native.HARDWAREINPUT
// Assembly: WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad
// MVID: 776EB3EF-00F5-4F48-8D79-09AC1BD5E956
// Assembly location: C:\Git\alexwnovak\JumpBot\JumpBot\packages\InputSimulator.1.0.4.0\lib\net20\WindowsInput.dll

namespace JumpBot.Native
{
   /// <summary>
   /// The HARDWAREINPUT structure contains information about a simulated message generated by an input device other than a keyboard or mouse.  (see: http://msdn.microsoft.com/en-us/library/ms646269(VS.85).aspx)
   ///             Declared in Winuser.h, include Windows.h
   /// 
   /// </summary>
   internal struct HARDWAREINPUT
   {
      /// <summary>
      /// Value specifying the message generated by the input hardware.
      /// 
      /// </summary>
      public uint Msg;
      /// <summary>
      /// Specifies the low-order word of the lParam parameter for uMsg.
      /// 
      /// </summary>
      public ushort ParamL;
      /// <summary>
      /// Specifies the high-order word of the lParam parameter for uMsg.
      /// 
      /// </summary>
      public ushort ParamH;
   }
}
